title: Philo's Blog
header-img: "img/green.jpg"
baseurl: ""
url: "philowong"

owner:
  name: "PhiloWong"
  email: yqw535@gmail.com

paginate: 8

timezone: Asia/Shanghai

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      author: "PhiloWong"

gems: [jekyll-paginate]

theme: jekyll-theme-cayman